### ISSUE TITLE
Blog-posts: no spaces between date and words

### ISSUE THREAD

**Issue by digi-tales** [pftnhr/yellow-karlskrona#2]
Thank you for the theme.
I have discovered a small error in the display of the date of the blog posts:  There are no spaces between date and words (see screen shot). Maybe it´s only in german. 
![Screenshot](https://github.com/pftnhr/yellow-karlskrona/assets/102251136/9407b2ab-8672-4f7c-a687-69f248c29793)

**Comment by pftnhr** [comment]
Thank you for reporting the error. I have fixed it. Can you please test if it is displayed correctly now?

**Comment by digi-tales** [comment]
Now it is displayed correctly. Thanks!
