### ISSUE TITLE
"Making notices" doesn´t show colors

### ISSUE THREAD

**Issue by digi-tales** [pftnhr/yellow-karlskrona#3]
Discovered another error: 
Making notices doesn´t work, when I use one of these below nothing is shown except the the text without the `!`. 
```
! Here's a notice with warning
!! Here's a notice with error
!!! Here's a notice with tip
```
By the way: Beautiful theme!

**Comment by pftnhr** [comment]
I have not provided notes in different colours. But you can simply add the CSS classes `.notice1`, `.notice2` and `.notice3` to the stylesheet. Or you can create an extra stylesheet with the three classes and then link it in the header.

> By the way: Beautiful theme!

Thank you!

**Comment by digi-tales** [comment]
Thanks for the advice, I will try it, but my CSS skills are very limited.

**Comment by pftnhr** [comment]
I'll see if I can add the classes over the next few days.

**Comment by digi-tales** [comment]
Managed to add CSS classes, with copy&paste from another yellow theme. Maybe not the most elegant way, but it works.

**Comment by pftnhr** [comment]
I have updated the theme and integrated Pico CSS v2.0.3 and the styles for the `notice` classes.
